CREATE TABLE IF NOT EXISTS character_status_points (
  `char_id` INT(10) UNSIGNED NOT NULL,
  `class_index` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `available` INT(10) UNSIGNED DEFAULT 0,
  `attr_distributed` INT(10) UNSIGNED DEFAULT 0,
  `attr_str` INT(10) UNSIGNED DEFAULT 0,
  `attr_con` INT(10) UNSIGNED DEFAULT 0,
  `attr_dex` INT(10) UNSIGNED DEFAULT 0,
  `attr_int` INT(10) UNSIGNED DEFAULT 0,
  `attr_wit` INT(10) UNSIGNED DEFAULT 0,
  `attr_men` INT(10) UNSIGNED DEFAULT 0,
  `status_distributed` INT(10) UNSIGNED DEFAULT 0,
  `status_pdef` INT(10) UNSIGNED DEFAULT 0,
  `status_mdef` INT(10) UNSIGNED DEFAULT 0,
  `status_hp` INT(10) UNSIGNED DEFAULT 0,
  `status_mp` INT(10) UNSIGNED DEFAULT 0,
  `status_cp` INT(10) UNSIGNED DEFAULT 0,
  `status_patk` INT(10) UNSIGNED DEFAULT 0,
  `status_matk` INT(10) UNSIGNED DEFAULT 0,
  `status_accuracy` INT(10) UNSIGNED DEFAULT 0,
  `status_evasion` INT(10) UNSIGNED DEFAULT 0,
  `status_crit` INT(10) UNSIGNED DEFAULT 0,
  `karma_penalty_attr` INT(10) UNSIGNED DEFAULT 0,
  `source_level_points` INT(10) UNSIGNED DEFAULT 0,
  `source_quest_points` INT(10) UNSIGNED DEFAULT 0,
  `source_raid_points` INT(10) UNSIGNED DEFAULT 0,
  `source_siege_points` INT(10) UNSIGNED DEFAULT 0,
  `source_pvp_points` INT(10) UNSIGNED DEFAULT 0,
  `source_karma_points` INT(10) UNSIGNED DEFAULT 0,
  `source_chest_points` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `version` INT(10) UNSIGNED DEFAULT 1,
  PRIMARY KEY (`char_id`,`class_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
