StatusPointsEnabled=true
StartingStatusPointsFromHenna=true
PDefPerPoint=1
MaxDexPoints=8
MaxWitPoints=8
MaxAttackSpeedPoints=8
MaxMagicAttackSpeedPoints=8
MaxMovementSpeedPoints=8
ResetItemId=9143
ResetItemCount=1
ResetAdena=100000
PremiumExemptFromResetCost=false
