# ============================================================
#                          Olympiad
# ============================================================

OlympiadEnabled = True
OlyStartTime = 18
OlyMin = 00
OlyCPeriod = 21600000
OlyBattle = 360000
OlyWPeriod = 604800000
OlyVPeriod = 86400000
OlyWaitTime = 60
OlyWaitBattle = 60
OlyWaitEnd = 40
OlyStartPoints = {{OlyStartPoints}}
OlyWeeklyPoints = 3
OlyMinMatchesToBeClassed = 9
OlyClassedParticipants = 5
OlyNonClassedParticipants = 9
OlyClassedReward = 6651-50
OlyNonClassedReward = 6651-30
OlyGPPerPoint = 1000
OlyHeroPoints = 300
OlyRank1Points = 100
OlyRank2Points = 75
OlyRank3Points = 55
OlyRank4Points = 40
OlyRank5Points = 30
OlyMaxPoints = 10
OlyAnnounceGames = True
OlyDividerClassed = 3
OlyDividerNonClassed = 5
OlyMaxEnchant = -1
OlyShowMonthlyWinners = True

# ============================================================
#                  Seven Signs && Festival
# ============================================================

SevenSignsBypassPrerequisites = False
FestivalMinPlayer = 5
MaxPlayerContrib = 1000000000

# ============================================================
#                       Four Sepulchers
# ============================================================

NeededPartyMembers = 4

# ============================================================
#                        Dimension Rift
# ============================================================

RiftMinPartySize = 2
AutoJumpsDelayMin = 8
AutoJumpsDelayRnd = 5
RecruitCost = 21
SoldierCost = 24
OfficerCost = 27
CaptainCost = 30
CommanderCost = 33
HeroCost = 36
AnakazelPortChance = 15

# ============================================================
#                         Lottery
# ============================================================

LotteryPrize = 50000
LotteryTicketPrice = 2000
Lottery5NumberRate = 0.6
Lottery4NumberRate = 0.2
Lottery3NumberRate = 0.2
Lottery2and1NumberPrize = 200

# ============================================================
#                     Fishing Tournament
# ============================================================

AllowFishChampionship = True
FishChampionshipRewardItemId = 57
FishChampionshipReward1 = 800000
FishChampionshipReward2 = 500000
FishChampionshipReward3 = 300000
FishChampionshipReward4 = 200000
FishChampionshipReward5 = 100000

CofferPriceId = 57
CofferPriceCount = 50000

AllowEventCommands = True

# ============================================================
#             CTF Event Engine (Capture The Flag)
# ============================================================

CTFEventEnabled = False
CTFEventInterval = 00:00,04:00,08:00,12:00,16:00,20:00
CTFEventParticipationTime = 1
CTFEventRunningTime = 3
CTFNpcLocName = Giran Town
CTFEventParticipationNpcId = 50004
CTFEventFirstTeamHeadquartersId = 50005
CTFEventSecondTeamHeadquartersId = 50006
CTFEventFirstTeamFlag = 6718
CTFEventSecondTeamFlag = 6718
CTFEventCaptureSkillId = 1034
CTFEventParticipationFee = 57,10000
CTFEventParticipationNpcCoordinates = 83425,148585,-3406,0
CTFEventMinPlayersInTeams = 1
CTFEventMaxPlayersInTeams = 20
CTFEventMinPlayerLevel = 52
CTFEventMaxPlayerLevel = 85
CTFEventRespawnTeleportDelay = 10
CTFEventStartLeaveTeleportDelay = 10
CTFEventTeam1Name = Blue
CTFEventTeam1Coordinates = 148607,46719,-3414
CTFEventTeam1FlagCoordinates = 148314,46715,-3412
CTFEventTeam2Name = Red
CTFEventTeam2Coordinates = 150439,46731,-3414
CTFEventTeam2FlagCoordinates = 150686,46713,-3414
CTFEventReward = 57-100000;4037-20
CTFEventTargetTeamMembersAllowed = True
CTFEventScrollsAllowed = False
CTFEventPotionsAllowed = False
CTFEventSummonByItemAllowed = False
CTFDoorsToOpen = 24190001;24190002;24190003;24190004
CTFDoorsToClose = 24190001;24190002;24190003;24190004
CTFRewardTeamTie = False
CTFEventEffectsRemoval = 0
CTFEventFighterBuffs = 1086,1;1068,3
CTFEventMageBuffs = 1086,1;1068,3
AllowDlgCTFInvite = False
CTFEventMaxParticipantsPerIP = 0

# ============================================================
#             Deathmatch Event Engine
# ============================================================

DMEventEnabled = False
DMEventInterval = 01:00,05:00,09:00,13:00,17:00,21:00
DMEventParticipationTime = 5
DMEventRunningTime = 5
DMNpcLocName = Giran Town
DMEventParticipationNpcId = 50007
DMEventParticipationFee = 57,10000
DMEventParticipationNpcCoordinates = 82838,148624,-3472,0
DMEventMinPlayers = 2
DMEventMaxPlayers = 300
DMEventMinPlayerLevel = 1
DMEventMaxPlayerLevel = 80
DMEventPlayerCoordinates = 148476,46061,-3411;150480,47444,-3411
DMEventRespawnTeleportDelay = 10
DMEventStartLeaveTeleportDelay = 10
DMShowTopRank = True
DMTopRank = 10
DMRewardFirstPlayers = 3
DMEventReward = 4037-50;57-50000|4037-40;57-40000|4037-30;57-30000
DMRewardPlayersTie = False
DMEventScrollsAllowed = False
DMEventPotionsAllowed = False
DMEventSummonByItemAllowed = False
DMDoorsToOpen = 24190001;24190002;24190003;24190004
DMDoorsToClose = 24190001;24190002;24190003;24190004
DMEventEffectsRemoval = 2
DMEventFighterBuffs = 1086,1;1068,3
DMEventMageBuffs = 1059,3;1085,3
DMDisabledForClasses = 16,97,30,105,43,112
AllowDlgDMInvite = False
DMEventMaxParticipantsPerIP = 0

# ============================================================
#             Last Man Event Engine
# ============================================================

LMEventEnabled = False
LMEventInterval = 02:00,06:00,10:00,14:00,18:00,22:00
LMEventParticipationTime = 5
LMEventHero = False
LMEventHeroDays = 1
LMEventRunningTime = 10
LMEventPlayerCredits = 1
LMNpcLocName = Giran Town
LMEventParticipationNpcId = 50007
LMEventParticipationFee = 57,10000
LMEventParticipationNpcCoordinates = 83425,148585,-3406,0
LMEventMinPlayers = 2
LMEventMaxPlayers = 100
LMEventMinPlayerLevel = 1
LMEventMaxPlayerLevel = 80
LMEventPlayerCoordinates = 148796,46725,-3408;150131,46740,-3413;149413,46725,-3408;149343,47310,-3408;149324,46216,-3408
LMEventRespawnTeleportDelay = 10
LMEventStartLeaveTeleportDelay = 10
LMEventReward = 4037-50;57-100000
LMRewardPlayersTie = False
LMEventScrollsAllowed = False
LMEventPotionsAllowed = False
LMEventSummonByItemAllowed = False
LMDoorsToOpen = 24190001;24190002;24190003;24190004
LMDoorsToClose = 24190001;24190002;24190003;24190004
LMEventEffectsRemoval = 0
LMEventFighterBuffs = 1086,1;1068,3
LMEventMageBuffs = 1059,3;1085,3
LMDisabledForClasses = 16,97,30,105,43,112
AllowDlgLMInvite = False
LMEventMaxParticipantsPerIP = 0

# ============================================================
#             TvT Event Engine (Team vs Team)
# ============================================================

TvTEventEnabled = False
TvTEventInterval = 03:00,07:00,11:00,15:00,19:00,23:00
TvTEventParticipationTime = 5
TvTEventRunningTime = 5
TvTNpcLocName = Giran Town
TvTEventParticipationNpcId = 50007
TvTEventParticipationNpcCoordinates = 83425,148585,-3406,0
TvTEventParticipationFee = 57,10000
TvTEventReward = 4037-50;57-50000
TvTEventMinPlayersInTeams = 1
TvTEventMaxPlayersInTeams = 300
TvTEventMinPlayerLevel = 76
TvTEventMaxPlayerLevel = 80
TvTEventRespawnTeleportDelay = 5
TvTEventStartLeaveTeleportDelay = 5
TvTEventTeam1Name = Omega
TvTEventTeam1Coordinates = 148476,46061,-3411
TvTEventTeam2Name = Alpha
TvTEventTeam2Coordinates = 150480,47444,-3411
TvTEventTargetTeamMembersAllowed = False
TvTEventScrollsAllowed = False
TvTEventPotionsAllowed = False
TvTEventSummonByItemAllowed = False
TvTDoorsToOpen = 24190001;24190002;24190003;24190004
TvTDoorsToClose = 24190001;24190002;24190003;24190004
TvTRewardTeamTie = False
TvTEventEffectsRemoval = 0
TvTEventFighterBuffs = 1086,1;1068,3
TvTEventMageBuffs = 1059,3;1085,3
TvTRewardOnlyKillers = False
TvTEventOnKill = title
TvTDisabledForClasses = 16,97,30,105,43,112
AllowDlgTvTInvite = False
TvTEventMaxParticipantsPerIP = 0
