# ============================================================
#         GC - Item Cleanup
# ============================================================

ItemsGcCleanupEnabled = True
ItemsGcCleanupTime = 120

# ============================================================
#         Item Level / Delevel Configuration
# ============================================================

ItemLevelDelevel_4037=1,0

# ============================================================
#         Premium VIP Items
# ============================================================

ItemPremium_5556=0,0,1
