# ============================================= #
#     Kamaloka Configuration                    #
# ============================================= #

# --- General Settings ---
ChannelingSkillId = 2013
MaxDailyEntries = {{MaxDailyEntries}}

# --- Locations ---
TeleportExitLocation = 83425,148585,-3406

# --- Rewards ---
RewardItemId = {{RewardItemId}}
RewardItemCount = {{RewardItemCount}}

# --- Monster Status (SOLO) ---
SoloMonsterLevelBonus = -5
SoloMonsterHpMultiplier = 1.7
SoloMonsterPdefMultiplier = 1.1
SoloMonsterMinHpMultiplier = 5.5
SoloMonsterMdefMultiplier = 1.1

# --- Monster Status (PARTY) ---
PartyMonsterLevelBonus = -5
PartyMonsterHpMultiplier = 1.9
PartyMonsterPdefMultiplier = 1.5
PartyMonsterMdefMultiplier = 1.5
PartyMonsterMinHpMultiplier = 5.0

# --- Raid Boss Status (SOLO) ---
SoloRaidPatkMultiplier = 0.125
SoloRaidMatkMultiplier = 0.125
SoloRaidMdefMultiplier = 0.2
SoloRaidPdefMultiplier = 0.5

# --- Raid Boss Status (PARTY) ---
PartyRaidPatkMultiplier = 0.25
PartyRaidMatkMultiplier = 0.25
PartyRaidMdefMultiplier = 0.5
