# ============================================================
#                           Players
# ============================================================

CancelLesserEffect = True

# % de regeneração da velocidade de regeneração normal - na base 1 = 100%.
HpRegenMultiplier = 1.
MpRegenMultiplier = 1.
CpRegenMultiplier = 1.

# Proteção do jogador após teleporte ou login em segundos, 0 para desabilitado
PlayerSpawnProtection = 10

# Proteção do jogador contra mobs (agro) após levantar da morte falsa; em segundos, 0 para desabilitado
PlayerFakeDeathUpProtection = 5

# Quantidade de HP restaurado ao reviver - na base 1 = 100%.
RespawnRestoreHP = 1.0

# Número máximo de slots permitidos para lojas privadas compra
MaxPvtStoreBuySlotsDwarf = 5
MaxPvtStoreBuySlotsOther = 4

# Número máximo de slots permitidos para lojas privadas venda
MaxPvtStoreSellSlotsDwarf = 4
MaxPvtStoreSellSlotsOther = 3

UseDeepBlueDropRules = True

AllowDelevel = True

DeathPenaltyChance = 5

# ============================================================
#                      Inventário / Depósito
# ============================================================

MaximumSlotsForNoDwarf = 80
MaximumSlotsForDwarf = 100
MaximumSlotsForPet = 12

WeightLimit = 100.

MaximumWarehouseSlotsForDwarf = 120
MaximumWarehouseSlotsForNoDwarf = 100
MaximumWarehouseSlotsForClan = 200
MaximumFreightSlots = 20

RegionBasedFreight = True

FreightPrice = 1000

# ============================================================
#                        Arguments
# ============================================================

AugmentationNGSkillChance = 15
AugmentationMidSkillChance = 30
AugmentationHighSkillChance = 45
AugmentationTopSkillChance = 60

AugmentationBaseStatChance = 1

AugmentationNGGlowChance = 0
AugmentationMidGlowChance = 40
AugmentationHighGlowChance = 70
AugmentationTopGlowChance = 100

# ============================================================
#                        Karma & PvP
# ============================================================

KarmaPlayerCanShop = False
KarmaPlayerCanTeleport = True
KarmaPlayerCanUseGK = False
KarmaPlayerCanTrade = True
KarmaPlayerCanUseWareHouse = True

CanGMDropEquipment = False

ListOfPetItems = 2375,3500,3501,3502,4422,4423,4424,4425,6648,6649,6650
ListOfNonDroppableItemsForPK = 57,1147,425,1146,461,10,2368,7,6,2370,2369

MinimumPKRequiredToDrop = 5

AwardPKKillPVPPoint = False

PvPVsNormalTime = 40000
PvPVsPvPTime = 20000

# ============================================================
#                             Grupo
# ============================================================

PartyXpCutoffMethod = level
PartyXpCutoffPercent = 3.0
PartyXpCutoffLevel = 20
PartyRange = 1500

# ============================================================
#                       GMs / Coisas de Admin
# ============================================================

DefaultAccessLevel = 0
GMHeroAura = False
GMStartupInvulnerable = True
GMStartupInvisible = True
GMStartupBlockAll = True
GMStartupAutoList = False

# ============================================================
#                           Petições
# ============================================================

PetitioningAllowed = True
MaxPetitionsPerPlayer = 5
MaxPetitionsPending = 25

# ============================================================
#                          Criação
# ============================================================

CraftingEnabled = True
DwarfRecipeLimit = 50
CommonRecipeLimit = 50

# ============================================================
#                      Skills / Classes
# ============================================================

AutoLearnSkills = True
LvlAutoLearnSkills = 80
MagicFailures = True
PerfectShieldBlockRate = 5
LifeCrystalNeeded = True
SpBookNeeded = True
EnchantSkillSpBookNeeded = True
DivineInspirationSpBookNeeded = True
SubClassWithoutQuests = False
SubclassRequireMimir = true
SubclassRequireFate = false

# ============================================================
#                        Config de Buffs
# ============================================================

MaxBuffsAmount = {{MAX_BUFFS}}
StoreSkillCooltime = True
ExpertisePenalty = True

# ============================================================
#                       Debug / Diagnóstico
# ============================================================

DebugMeleeAttack = False
