# =================================================================
#                               Rates
# =================================================================

# XP gain multiplier
RateXp = {{RATE_XP}}

# SP gain multiplier
RateSp = {{RATE_SP}}

# XP gain multiplier in a party
RatePartyXp = 1.5

# SP gain multiplier in a party
RatePartySp = 1.5

# ---------------------------------------#
#         Drop/Reward Configuration      #
# ---------------------------------------#

# Adena gain multiplier
RateDropCurrency = {{RATE_DROP}}

# Seal Stones gain multiplier.
RateDropSealStone = 1.

# Item drop multiplier
RateDropItems = {{RATE_DROP_ITEMS}}

# Spoil multiplier
RateDropSpoil = 1.5

# Herbs multiplier
RateDropHerbs = 0.8

# Manor fruit multiplier
RateDropManor = 1

# Quest configuration parameters.
RateQuestDrop = 1.
RateQuestReward = 1.
RateQuestRewardXP = 1.
RateQuestRewardSP = 1.
RateQuestRewardAdena = 1.

RateKarmaExpLost = 1
RateSiegeGuardsPrice = 1

# Player drop rate control, values in percentages.
PlayerDropLimit = 0
PlayerRateDrop = 0
PlayerRateDropItem = 0
PlayerRateDropEquip = 0
PlayerRateDropEquipWeapon = 0

# Player drop rate control with karma, values in percentages.
KarmaDropLimit = 10
KarmaRateDrop = 40
KarmaRateDropItem = 50
KarmaRateDropEquip = 40
KarmaRateDropEquipWeapon = 10

# Pet rate control. Default: 1, 1, 1
PetXpRate = 1.
PetFoodRate = 1
SinEaterXpRate = 1.

# ---------------------------------------#
#          Rates for Raid Bosses         #
# ---------------------------------------#

# XP gain multiplier from Grand Boss.
GrandBossRateXp = 1.
# SP gain multiplier from Grand Boss.
GrandBossRateSp = 1.
# Item drop multiplier from Grand Boss.
RateGrandDropItems = 1.

# XP gain multiplier from Raid Boss.
RaidBossRateXp = 1.
# SP gain multiplier from Raid Boss.
RaidBossRateSp = 1.
# Item drop multiplier from Raid Boss.
RateRaidDropItems = 1.

# ---------------------------------------#
#      Rates for Premium Account         #
# ---------------------------------------#

PremiumRateXp = 2.
PremiumRateSp = 2.
PremiumRateDropCurrency = 2.
PremiumRateDropSealStone = 2.
PremiumRateDropItems = 2.
PremiumRateRaidDropItems = 2.
PremiumRateGrandDropItems = 2.
PremiumRateDropSpoil = 2.
PremiumRateQuestDrop = 2.
PremiumRateQuestReward = 2.
PremiumRateQuestRewardXP = 2.
PremiumRateQuestRewardSP = 2.
PremiumRateQuestRewardAdena = 2.

# Dynamic rates based on level
DynamicXp = False
DynamicXpRates = 1:5;2:5;3:5;4:5;5:5;6:4;7:0.5;8:0.25
