# ============================================================
#                            Sieges
# ============================================================

# Length of siege before the countdown (in minutes)
SiegeLength = {{SiegeLength}}

# Minimum clan level to register.
SiegeClanMinLevel = {{SiegeClanMinLevel}}

# Max numbers of clans that can register on each side.
AttackerMaxClans = {{AttackerMaxClans}}
DefenderMaxClans = {{DefenderMaxClans}}

# ============================================================
#                     Siegable Halls
# ============================================================

# Minimum clan level to register.
ChSiegeClanMinLevel = 4

# Max numbers of clans that can register.
ChAttackerMaxClans = 10

# Enable command .siege
SiegeInfo = False
