#===================================================================================
# DeepL Translator 
#===================================================================================

#Chave de Autenticacao da API DeepL
DeeplAuthKey = {{DeeplAuthKey}}

#Contexto da Traducao
DeeplContext = This is text from the fantasy game Lineage 2. Follow these rules strictly: 1. Do not translate proper nouns or game-specific terms (names of characters, monsters, skills, items, locations). 2. The word 'Quest' must remain in English. 3. CRITICAL: Do not translate, alter, or remove any special placeholders. These placeholders often start with '$' (like $s1, $s2), are enclosed in '%' (like %playername%, %quest_name%), or are enclosed in '<' and '>' (like <fstring>). Preserve them exactly as they are in the original text. 4. IMPORTANT: This text is part of an HTML document. Only translate the visible text content. Do not translate or modify any HTML tags or their attributes, especially attributes like 'action', 'href', 'width', or 'height'.

#Lista de Exclusao de Traducao
DoNotTranslate = data/html/CommunityBoard/,data/html/mods
